print ("*************Welcome to Defect Prediction Tool!!**********")
sink("D:\\HACKATHON\\DPP\\RScripts\\out.txt")
output <- system("cmd.exe /c git clone https://github.com/exbalar/myApp.git", intern=TRUE)
output <- system("cmd.exe /c D:")
output <- system("cmd.exe /c cd D:\\hackathon\\DPT\\myApp\\ && git.exe log", intern=TRUE)
print(output)
